# ---------- Build Stage ----------
FROM node:20-alpine AS builder

WORKDIR /app

# copy package ก่อน (cache layer)
COPY package*.json ./

RUN npm install

# copy source code
COPY . .

# build (Vite → dist/)
RUN npm run build


# ---------- Serve Stage ----------
FROM nginx:alpine

# ลบ config default
RUN rm -rf /etc/nginx/conf.d/default.conf

# copy nginx config (optional แต่แนะนำ)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# copy build จาก stage ก่อน
COPY --from=builder /app/dist /usr/share/nginx/html

# expose port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
