pipeline {
    agent any

    environment {
        ARM_CLIENT_ID = credentials('azure-client-id')
        ARM_CLIENT_SECRET = credentials('azure-client-secret')
        ARM_TENANT_ID = credentials('azure-tenant-id')
        ARM_SUBSCRIPTION_ID = credentials('azure-subscription-id')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/D1n0cute/project-server-less.git'
            }
        }

        stage('Azure Login') {
            steps {
                sh '''
                az login --service-principal \
                  -u $ARM_CLIENT_ID \
                  -p $ARM_CLIENT_SECRET \
                  --tenant $ARM_TENANT_ID

                az account set --subscription $ARM_SUBSCRIPTION_ID
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                terraform -chdir=terraform init
                terraform -chdir=terraform apply -auto-approve
                '''
            }
        }

        stage('Get kubeconfig from AKS') {
            steps {
                sh '''
                az aks get-credentials \
                  --resource-group aks-rg \
                  --name my-aks-cluster \
                  --overwrite-existing
                '''
            }
        }

        stage('Deploy Frontend') {
            steps {
                sh '''
                cd ansible
                ansible-playbook -i inventory/prod playbooks/frontend.yml
                '''
            }
        }
    }
}
