pipeline {
    agent any

    environment {
        ARM_CLIENT_ID = credentials('azure-client-id')
        ARM_CLIENT_SECRET = credentials('azure-client-secret')
        ARM_TENANT_ID = credentials('azure-tenant-id')
        ARM_SUBSCRIPTION_ID = credentials('azure-subscription-id')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/D1n0cute/project-server-less.git'
            }
        }

        stage('Azure Login') {
            steps {
                sh '''
                az login --service-principal \
                  -u $ARM_CLIENT_ID \
                  -p $ARM_CLIENT_SECRET \
                  --tenant $ARM_TENANT_ID

                az account set --subscription $ARM_SUBSCRIPTION_ID
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                terraform -chdir=terraform init
                terraform -chdir=terraform apply -auto-approve
                '''
            }
        }

        stage('Get kubeconfig') {
            steps {
                sh '''
                az aks get-credentials \
                  --resource-group aks-rg \
                  --name my-aks-cluster \
                  --overwrite-existing
                '''
            }
        }

        stage('Bootstrap Ingress Controller') {
            steps {
                sh '''
                kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
                '''
            }
        }

        stage('Wait Ingress Controller Ready') {
            steps {
                sh '''
                kubectl wait -n ingress-nginx \
                  --for=condition=ready pod \
                  --selector=app.kubernetes.io/component=controller \
                  --timeout=180s
                '''
            }
        }

        stage('Deploy Backend') {
            steps {
                sh '''
                cd ansible
                ansible-playbook -i inventory/prod playbooks/backend.yml
                kubectl rollout restart deployment backend

                '''
            }
        }

        stage('Deploy Ingress Rules') {
            steps {
                sh '''
                cd ansible
                ansible-playbook -i inventory/prod playbooks/ingress.yml
                kubectl rollout restart deployment ingress-nginx-controller -n ingress-nginx
                '''
            }
        }
    }
}
