pipeline {
    agent any

    environment {
        BE_IMAGE = "pannatronkanla/backend"
        TAG = "latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test Backend') {
            when {
                changeset "backend/**"
            }

            steps {
                sh '''
                echo "=== Testing Backend ==="

                cd backend

                if [ -d venv ]; then rm -rf venv; fi

                python3 -m venv venv
                . venv/bin/activate

                pip install --upgrade pip
                pip install -r requirements.txt

                pytest
                '''
            }
        }

        stage('Docker Build') {
            when {
                changeset "backend/**"
            }

            steps {
                sh '''
                docker build -t $BE_IMAGE:latest ./backend
                '''
            }
        }

        stage('Push Docker Hub') {
            when {
                changeset "backend/**"
            }

            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $BE_IMAGE:latest
                    '''
                }
            }
        }

        stage('Cleanup') {
            steps {
                sh '''
                docker image prune -f || true
                docker logout || true
                '''
            }
        }
    }
}
